name: CI-Security

on:
  push:
  pull_request:

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      - name: Ensure mvnw is executable
        run: chmod +x mvnw

      - name: Run SpotBugs (SAST) + Dependency-Check (SCA)
        run: ./mvnw -B verify -s $GITHUB_WORKSPACE/.mvn/settings.xml
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}

      - name: Upload Dependency-Check report (SCA)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

      - name: Upload SpotBugs report (SAST)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-xml
          path: target/spotbugsXml.xml
